# Generated by Django 4.2.4 on 2023-10-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surface', '0002_modelsurface_latex_expr_alter_modelsurface_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelsurface',
            name='img',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='modelsurface',
            name='latex_img',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='modelsurface',
            name='link',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='modelsurface',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
